#!/bin/sh

#--------------------------------------------------------------------
# FlightMode
#--------------------------------------------------------------------

case "$fn" in
    # Check bluetooth status
    "bluetooth:status")
        defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState | \
        awk '{ if($1 != 0) {print "Bluetooth: ON"} else { print "Bluetooth: OFF" }  }'
    ;;
    
    
    # Enable bluetooth
    "bluetooth:enable")
        echo "${GREEN}Bluetooth enabled{NC}"
        sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 1 && \
        sudo killall -HUP blued
    ;;
    
    
    # Disable bluetooth
    "bluetooth:disable")
        echo "${GREEN}Bluetooth disabled${NC}"
        sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 0 && \
        sudo killall -HUP blued
    ;;
esac
